
using Sitecore.Data;
#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Elision.Fields
{
    public static class TwitterCardsMetaFieldIDs
    {
        public static readonly ID TemplateId = new ID("{035D7D88-5A24-41D8-8D5F-CDDFF0397295}");
        public static readonly ID TwitterCardContentCreator = new ID("{F4DED7B3-8B6F-46D8-902C-1C119BDA1699}");
        public static readonly ID TwitterCardDescription = new ID("{5B3DD1A3-40F8-42BE-900E-53FA38195AF1}");
        public static readonly ID TwitterCardImage = new ID("{BA3C147E-035B-478F-829B-FE233775648F}");
        public static readonly ID TwitterCardSite = new ID("{BA005D3B-393D-4594-8508-70A503925DCD}");
        public static readonly ID TwitterCardSiteId = new ID("{217988BC-4DDE-4B44-A688-DFB8F69C6061}");
        public static readonly ID TwitterCardTitle = new ID("{0181FE49-A838-496D-8690-935282E599F3}");
        public static readonly ID TwitterCardType = new ID("{579ED843-06B5-4E31-9B98-0D4B12E418AB}");
    }
    public static class TwitterCardsMetaFieldNames
    {
        public const string TemplateName = "TwitterCardsMeta";
        public const string TwitterCardContentCreator = "TwitterCardContentCreator";
        public const string TwitterCardDescription = "TwitterCardDescription";
        public const string TwitterCardImage = "TwitterCardImage";
        public const string TwitterCardSite = "TwitterCardSite";
        public const string TwitterCardSiteId = "TwitterCardSiteId";
        public const string TwitterCardTitle = "TwitterCardTitle";
        public const string TwitterCardType = "TwitterCardType";
    }
}
namespace Elision.Fields
{
    public static class ThemeEmbeddedResourceFieldIDs
    {
        public static readonly ID TemplateId = new ID("{06234046-5BC2-4457-87C2-6B09EBB797D3}");
        public static readonly ID ResourceCode = new ID("{1E0ED541-79D4-43C7-930E-2BED12B23B63}");
        public static readonly ID PageModes = new ID("{B7100C64-8316-44E7-926D-9F2FE164CD69}");
        public static readonly ID ResourceLocation = new ID("{575073A1-3DEF-47E6-B62A-D5BD2F94D6A7}");
        public static readonly ID SupportedDevices = new ID("{70AA35E0-E88C-4504-A512-58BBB4D10AAA}");
    }
    public static class ThemeEmbeddedResourceFieldNames
    {
        public const string TemplateName = "ThemeEmbeddedResource";
        public const string ResourceCode = "ResourceCode";
        public const string PageModes = "PageModes";
        public const string ResourceLocation = "ResourceLocation";
        public const string SupportedDevices = "SupportedDevices";
    }
}
namespace Elision.Fields
{
    public static class IconFieldsFieldIDs
    {
        public static readonly ID TemplateId = new ID("{08D7E131-535A-4865-9E89-BB7CBDC37947}");
        public static readonly ID Icon = new ID("{7188E751-4221-4C2B-85E3-AA26A0966FDA}");
    }
    public static class IconFieldsFieldNames
    {
        public const string TemplateName = "IconFields";
        public const string Icon = "Icon";
    }
}
namespace Elision.Fields
{
    public static class GeoLocationFieldIDs
    {
        public static readonly ID TemplateId = new ID("{100179BA-F484-4455-A76A-BF172B587180}");
        public static readonly ID Latitude = new ID("{0B7CC28C-ECEF-456C-A7D7-D89AE0D418FF}");
        public static readonly ID Longitude = new ID("{5D9B7C39-EC1B-4785-93EC-4915448FD41F}");
    }
    public static class GeoLocationFieldNames
    {
        public const string TemplateName = "GeoLocation";
        public const string Latitude = "Latitude";
        public const string Longitude = "Longitude";
    }
}
namespace Elision.Fields
{
    public static class ThemeFieldIDs
    {
        public static readonly ID TemplateId = new ID("{121B5A57-E9E8-4429-A41D-811CA98116E1}");
        public static readonly ID MvcAreaName = new ID("{0BE49B84-3F8C-48D9-93A5-770604D78323}");
    }
    public static class ThemeFieldNames
    {
        public const string TemplateName = "Theme";
        public const string MvcAreaName = "MvcAreaName";
    }
}
namespace Elision.Fields
{
    public static class ComponentsFolderFieldIDs
    {
        public static readonly ID TemplateId = new ID("{122AE27A-D84F-4C5E-8367-0F42C764976E}");
    }
    public static class ComponentsFolderFieldNames
    {
        public const string TemplateName = "ComponentsFolder";
    }
}
namespace Elision.Fields
{
    public static class ColorFieldsFieldIDs
    {
        public static readonly ID TemplateId = new ID("{15F2DCA3-97B7-46B2-AD68-02C7AAACD5E2}");
        public static readonly ID BackgroundColor = new ID("{926E6C42-0A2D-493F-829F-F7A95227B64D}");
        public static readonly ID ForegroundColor = new ID("{547FEDD6-CB0F-45D5-8B4F-54A6719873DF}");
    }
    public static class ColorFieldsFieldNames
    {
        public const string TemplateName = "ColorFields";
        public const string BackgroundColor = "BackgroundColor";
        public const string ForegroundColor = "ForegroundColor";
    }
}
namespace Elision.Fields
{
    public static class NavigationLevelsFieldsFieldIDs
    {
        public static readonly ID TemplateId = new ID("{1CDE63DB-4F0A-467D-A334-DD7192864278}");
        public static readonly ID IncludeTopLevel = new ID("{C8BA8AF6-FDB4-46FE-B0B4-1AE3B53FF24B}");
        public static readonly ID NavigationLevels = new ID("{2636D1F7-1CB7-4B90-8A8D-3B11CB030C76}");
    }
    public static class NavigationLevelsFieldsFieldNames
    {
        public const string TemplateName = "NavigationLevelsFields";
        public const string IncludeTopLevel = "IncludeTopLevel";
        public const string NavigationLevels = "NavigationLevels";
    }
}
namespace Elision.Fields
{
    public static class StructureRenderingParametersFieldIDs
    {
        public static readonly ID TemplateId = new ID("{1D5789F7-2B50-4BD1-9EA0-19195DECC84C}");
        public static readonly ID CssClass = new ID("{CEE8ACB0-808F-461D-A3D8-BC5A1A9888F3}");
        public static readonly ID ColorScheme = new ID("{35B7B14B-F1B2-4D06-95AD-B696917D26E5}");
    }
    public static class StructureRenderingParametersFieldNames
    {
        public const string TemplateName = "StructureRenderingParameters";
        public const string CssClass = "CssClass";
        public const string ColorScheme = "ColorScheme";
    }
}
namespace Elision.Fields
{
    public static class CssClassFieldsFieldIDs
    {
        public static readonly ID TemplateId = new ID("{21BA69C6-CAC9-47BD-83E2-894FD7FDBEA1}");
        public static readonly ID CssClass = new ID("{CEE8ACB0-808F-461D-A3D8-BC5A1A9888F3}");
    }
    public static class CssClassFieldsFieldNames
    {
        public const string TemplateName = "CssClassFields";
        public const string CssClass = "CssClass";
    }
}
namespace Elision.Fields
{
    public static class FragmentFieldIDs
    {
        public static readonly ID TemplateId = new ID("{231F2B92-0C3A-40D6-88CB-133A1DDAFD69}");
    }
    public static class FragmentFieldNames
    {
        public const string TemplateName = "Fragment";
    }
}
namespace Elision.Fields
{
    public static class CustomMenuItemRenderingParametersFieldIDs
    {
        public static readonly ID TemplateId = new ID("{2AFA6C84-51DA-46D9-B68B-1B00997CADCE}");
        public static readonly ID CssClass = new ID("{CEE8ACB0-808F-461D-A3D8-BC5A1A9888F3}");
    }
    public static class CustomMenuItemRenderingParametersFieldNames
    {
        public const string TemplateName = "CustomMenuItemRenderingParameters";
        public const string CssClass = "CssClass";
    }
}
namespace Elision.Fields
{
    public static class OpenGraphMetaFieldIDs
    {
        public static readonly ID TemplateId = new ID("{359D47A4-7DD7-465B-9060-04020CC90386}");
        public static readonly ID OgDescription = new ID("{475A8C93-A6CB-4D6B-A288-58FD09FB7A18}");
        public static readonly ID OgImage = new ID("{F046BEA2-BB06-4CEB-B87D-2F1A28A6D101}");
        public static readonly ID OgSiteName = new ID("{15D1129E-D78D-4EE4-A005-0CC1617A5F4D}");
        public static readonly ID OgTitle = new ID("{9CE2BFC9-04C1-429C-B388-152506E97078}");
        public static readonly ID OgType = new ID("{4E4F0C39-6B77-43F5-AB56-8AEFAA395819}");
    }
    public static class OpenGraphMetaFieldNames
    {
        public const string TemplateName = "OpenGraphMeta";
        public const string OgDescription = "OgDescription";
        public const string OgImage = "OgImage";
        public const string OgSiteName = "OgSiteName";
        public const string OgTitle = "OgTitle";
        public const string OgType = "OgType";
    }
}
namespace Elision.Fields
{
    public static class NavigableFieldIDs
    {
        public static readonly ID TemplateId = new ID("{3B5F863D-692E-41E2-A2CA-B027227A2C87}");
        public static readonly ID NavigationText = new ID("{9638B7BE-396E-4A34-B050-F3AB26826229}");
        public static readonly ID ShowInInteriorNavigation = new ID("{F70C036B-6D13-4C73-8E18-D247DAAB5B1F}");
        public static readonly ID ShowInPrimaryNavigation = new ID("{20F9494E-0190-47A0-8A5B-E64F67E801B9}");
    }
    public static class NavigableFieldNames
    {
        public const string TemplateName = "Navigable";
        public const string NavigationText = "NavigationText";
        public const string ShowInInteriorNavigation = "ShowInInteriorNavigation";
        public const string ShowInPrimaryNavigation = "ShowInPrimaryNavigation";
    }
}
namespace Elision.Fields
{
    public static class FragmentContainerFieldIDs
    {
        public static readonly ID TemplateId = new ID("{3D5238BC-8767-4AB2-AD85-C78530DDA254}");
    }
    public static class FragmentContainerFieldNames
    {
        public const string TemplateName = "FragmentContainer";
    }
}
namespace Elision.Fields
{
    public static class DocumentHeadingRenderingParametersFieldIDs
    {
        public static readonly ID TemplateId = new ID("{3F21443D-7E31-4412-BA58-0B553FC1E531}");
        public static readonly ID TextAlign = new ID("{144EF311-3003-40AF-AC2C-DDEED3D4A64D}");
        public static readonly ID CssClass = new ID("{CEE8ACB0-808F-461D-A3D8-BC5A1A9888F3}");
        public static readonly ID HeadingLevel = new ID("{3D0F3166-9579-494E-A76C-75E5A47BB451}");
    }
    public static class DocumentHeadingRenderingParametersFieldNames
    {
        public const string TemplateName = "DocumentHeadingRenderingParameters";
        public const string TextAlign = "TextAlign";
        public const string CssClass = "CssClass";
        public const string HeadingLevel = "HeadingLevel";
    }
}
namespace Elision.Fields
{
    public static class Template_FieldFieldIDs
    {
        public static readonly ID TemplateId = new ID("{455A3E98-A627-4B40-8035-E683A0331AC7}");
        public static readonly ID Hide_With_Standard_Fields = new ID("{6EF51419-ECEA-452A-B5C6-7E0ED69DCC45}");
    }
    public static class Template_FieldFieldNames
    {
        public const string TemplateName = "Template field";
        public const string Hide_With_Standard_Fields = "Hide with standard fields";
    }
}
namespace Elision.Fields
{
    public static class CssClassOptionFieldIDs
    {
        public static readonly ID TemplateId = new ID("{4A32CB4E-1BB8-4A64-B1BD-55B8CE0D09F6}");
        public static readonly ID CssClass = new ID("{E0432202-BEE9-43C3-91CA-645954DCC398}");
    }
    public static class CssClassOptionFieldNames
    {
        public const string TemplateName = "CssClassOption";
        public const string CssClass = "CssClass";
    }
}
namespace Elision.Fields
{
    public static class ResponsiveImageProfileFieldsFieldIDs
    {
        public static readonly ID TemplateId = new ID("{4CBAAC97-7FAE-4217-B89D-D53F8F640841}");
        public static readonly ID ResponsiveImageProfile = new ID("{761F1C03-27AF-4A26-852F-FB78C7CBBB2F}");
    }
    public static class ResponsiveImageProfileFieldsFieldNames
    {
        public const string TemplateName = "ResponsiveImageProfileFields";
        public const string ResponsiveImageProfile = "ResponsiveImageProfile";
    }
}
namespace Elision.Fields
{
    public static class PhysicalLocationFieldIDs
    {
        public static readonly ID TemplateId = new ID("{5C4C2671-9F9F-43DB-8B56-448C3D5C1F53}");
        public static readonly ID Address = new ID("{1174617A-4F00-4A6D-BC5F-F73897D83AC7}");
        public static readonly ID Address2 = new ID("{75886D73-95FD-4B88-97F7-23D5B5994136}");
        public static readonly ID City = new ID("{65C64F2C-6E54-47C5-BA3B-EC941FD0B97F}");
        public static readonly ID PostalCode = new ID("{2F68ADFE-047A-485B-909E-C3E7FB7B830C}");
        public static readonly ID State = new ID("{CB11B366-DFC2-482D-96C8-C5A99CAAC47B}");
    }
    public static class PhysicalLocationFieldNames
    {
        public const string TemplateName = "PhysicalLocation";
        public const string Address = "Address";
        public const string Address2 = "Address2";
        public const string City = "City";
        public const string PostalCode = "PostalCode";
        public const string State = "State";
    }
}
namespace Elision.Fields
{
    public static class HideWithStandardFieldsFieldIDs
    {
        public static readonly ID TemplateId = new ID("{63B02666-1515-4898-8827-50CF62EA278B}");
        public static readonly ID Hide_With_Standard_Fields = new ID("{6EF51419-ECEA-452A-B5C6-7E0ED69DCC45}");
    }
    public static class HideWithStandardFieldsFieldNames
    {
        public const string TemplateName = "HideWithStandardFields";
        public const string Hide_With_Standard_Fields = "Hide with standard fields";
    }
}
namespace Elision.Fields
{
    public static class CascadableFieldIDs
    {
        public static readonly ID TemplateId = new ID("{653EF58B-1575-4A52-AAF2-DE5AB691D665}");
        public static readonly ID CascadePlaceholders = new ID("{03AD4613-0167-420A-8B3F-3CB6CCF3B738}");
    }
    public static class CascadableFieldNames
    {
        public const string TemplateName = "Cascadable";
        public const string CascadePlaceholders = "CascadePlaceholders";
    }
}
namespace Elision.Fields
{
    public static class SearchableFieldIDs
    {
        public static readonly ID TemplateId = new ID("{6DAD8E76-DA0D-4093-9E8C-D4162A23C562}");
        public static readonly ID HideFromSiteSearch = new ID("{3C4D4755-8FB1-40F2-B236-BE1E0B552A84}");
    }
    public static class SearchableFieldNames
    {
        public const string TemplateName = "Searchable";
        public const string HideFromSiteSearch = "HideFromSiteSearch";
    }
}
namespace Elision.Fields
{
    public static class PageMetaFieldsFieldIDs
    {
        public static readonly ID TemplateId = new ID("{6F0FABD4-47AB-461A-959E-B4D292EE01E5}");
        public static readonly ID BlockSearchEngineIndexing = new ID("{0ED18C8B-E06A-4F49-8F9E-8346F1A3294C}");
        public static readonly ID BlockSearchEngineLinkFollowing = new ID("{7FB8D83D-C981-49D9-B352-953E5C6BE7CF}");
        public static readonly ID BrowserTitle = new ID("{D6CB41B5-9467-4C42-95AC-B62584A1F5F0}");
        public static readonly ID CanonicalUrl = new ID("{C0AD316F-EEC8-494D-A30A-356C10E8853E}");
        public static readonly ID MetaDescription = new ID("{D62C4448-2E23-4393-939D-F489DCFB881E}");
        public static readonly ID MetaKeywords = new ID("{DEAD7283-98C8-4AB8-924E-0DEB00858EFB}");
    }
    public static class PageMetaFieldsFieldNames
    {
        public const string TemplateName = "PageMetaFields";
        public const string BlockSearchEngineIndexing = "BlockSearchEngineIndexing";
        public const string BlockSearchEngineLinkFollowing = "BlockSearchEngineLinkFollowing";
        public const string BrowserTitle = "BrowserTitle";
        public const string CanonicalUrl = "CanonicalUrl";
        public const string MetaDescription = "MetaDescription";
        public const string MetaKeywords = "MetaKeywords";
    }
}
namespace Elision.Fields
{
    public static class ResponsiveImageRenderingParametersFieldIDs
    {
        public static readonly ID TemplateId = new ID("{762C3224-5160-4A6B-BA48-5CEEAEB51C4E}");
        public static readonly ID ResponsiveImageProfile = new ID("{761F1C03-27AF-4A26-852F-FB78C7CBBB2F}");
        public static readonly ID CssClass = new ID("{CEE8ACB0-808F-461D-A3D8-BC5A1A9888F3}");
    }
    public static class ResponsiveImageRenderingParametersFieldNames
    {
        public const string TemplateName = "ResponsiveImageRenderingParameters";
        public const string ResponsiveImageProfile = "ResponsiveImageProfile";
        public const string CssClass = "CssClass";
    }
}
namespace Elision.Fields
{
    public static class ResponsiveImageProfileFieldIDs
    {
        public static readonly ID TemplateId = new ID("{782B9364-9641-4353-9AFE-BCF5E0E44B6C}");
        public static readonly ID DefaultImageSize = new ID("{964D48DE-984E-4108-B490-5942832DFBEA}");
    }
    public static class ResponsiveImageProfileFieldNames
    {
        public const string TemplateName = "ResponsiveImageProfile";
        public const string DefaultImageSize = "DefaultImageSize";
    }
}
namespace Elision.Fields
{
    public static class LinkFieldIDs
    {
        public static readonly ID TemplateId = new ID("{79A0DCB4-A24C-4422-883D-E67DFDCF58C3}");
        public static readonly ID Link = new ID("{370823A6-462D-4E98-A426-C2E58E28A175}");
    }
    public static class LinkFieldNames
    {
        public const string TemplateName = "Link";
        public const string Link = "Link";
    }
}
namespace Elision.Fields
{
    public static class ColorSchemeFieldsFieldIDs
    {
        public static readonly ID TemplateId = new ID("{7CBBB87E-7EA0-4BF6-AE5D-EE0437722BF0}");
        public static readonly ID ColorScheme = new ID("{35B7B14B-F1B2-4D06-95AD-B696917D26E5}");
    }
    public static class ColorSchemeFieldsFieldNames
    {
        public const string TemplateName = "ColorSchemeFields";
        public const string ColorScheme = "ColorScheme";
    }
}
namespace Elision.Fields
{
    public static class ThemableFieldIDs
    {
        public static readonly ID TemplateId = new ID("{7D0DCCF0-891D-4A14-9B1D-2251DF4B0FB7}");
        public static readonly ID Theme = new ID("{F318342F-A549-47F7-BD88-25086B46B9D9}");
    }
    public static class ThemableFieldNames
    {
        public const string TemplateName = "Themable";
        public const string Theme = "Theme";
    }
}
namespace Elision.Fields
{
    public static class CustomMenuRenderingParametersFieldIDs
    {
        public static readonly ID TemplateId = new ID("{7E928C8D-EBDD-4757-9284-755DC3832AF3}");
        public static readonly ID CssClass = new ID("{CEE8ACB0-808F-461D-A3D8-BC5A1A9888F3}");
        public static readonly ID ColorScheme = new ID("{35B7B14B-F1B2-4D06-95AD-B696917D26E5}");
    }
    public static class CustomMenuRenderingParametersFieldNames
    {
        public const string TemplateName = "CustomMenuRenderingParameters";
        public const string CssClass = "CssClass";
        public const string ColorScheme = "ColorScheme";
    }
}
namespace Elision.Fields
{
    public static class SearchSynonymsFieldIDs
    {
        public static readonly ID TemplateId = new ID("{82512830-A4B0-46DA-A66C-F791BA2AAC59}");
        public static readonly ID Synonyms = new ID("{FAC4C732-DE08-46DE-9882-DF21D92B9A85}");
    }
    public static class SearchSynonymsFieldNames
    {
        public const string TemplateName = "SearchSynonyms";
        public const string Synonyms = "Synonyms";
    }
}
namespace Elision.Fields
{
    public static class TextOptionFieldIDs
    {
        public static readonly ID TemplateId = new ID("{8E2231BB-DAC2-43AF-B22E-6580440DE200}");
        public static readonly ID Text = new ID("{57A8F63A-4DA8-42C8-B741-DE1E2CBA9D54}");
    }
    public static class TextOptionFieldNames
    {
        public const string TemplateName = "TextOption";
        public const string Text = "Text";
    }
}
namespace Elision.Fields
{
    public static class ThemeLinkedResourceFieldIDs
    {
        public static readonly ID TemplateId = new ID("{9D560638-C289-4C6F-ADF2-06760928ED55}");
        public static readonly ID ResourceLink = new ID("{11B3B1A5-59F9-4EC2-A0DA-A1A6DAF1B944}");
        public static readonly ID PageModes = new ID("{B7100C64-8316-44E7-926D-9F2FE164CD69}");
        public static readonly ID ResourceLocation = new ID("{575073A1-3DEF-47E6-B62A-D5BD2F94D6A7}");
        public static readonly ID SupportedDevices = new ID("{70AA35E0-E88C-4504-A512-58BBB4D10AAA}");
    }
    public static class ThemeLinkedResourceFieldNames
    {
        public const string TemplateName = "ThemeLinkedResource";
        public const string ResourceLink = "ResourceLink";
        public const string PageModes = "PageModes";
        public const string ResourceLocation = "ResourceLocation";
        public const string SupportedDevices = "SupportedDevices";
    }
}
namespace Elision.Fields
{
    public static class ImageFieldIDs
    {
        public static readonly ID TemplateId = new ID("{9E4FD01D-ADC9-42E9-A3E6-A7207733EA0F}");
        public static readonly ID Image = new ID("{A76D7B22-9734-4059-8749-7044A8B0FCBF}");
    }
    public static class ImageFieldNames
    {
        public const string TemplateName = "Image";
        public const string Image = "Image";
    }
}
namespace Elision.Fields
{
    public static class GeneratedNavigationRenderingParametersFieldIDs
    {
        public static readonly ID TemplateId = new ID("{9F34A98E-0EA8-4DFA-8801-43E01D1816D4}");
        public static readonly ID IncludeTopLevel = new ID("{C8BA8AF6-FDB4-46FE-B0B4-1AE3B53FF24B}");
        public static readonly ID NavigationLevels = new ID("{2636D1F7-1CB7-4B90-8A8D-3B11CB030C76}");
        public static readonly ID CssClass = new ID("{CEE8ACB0-808F-461D-A3D8-BC5A1A9888F3}");
        public static readonly ID ChildLinkClass = new ID("{5A6FCBB2-93C4-4458-8ACC-9AB713341055}");
        public static readonly ID ChildListClass = new ID("{C6EF88F6-CF6E-4415-9079-484950A4581F}");
        public static readonly ID ChildListItemClass = new ID("{9DE25D2B-4935-4A06-ACA2-BB56ED526A3C}");
        public static readonly ID TopLevelLinkClass = new ID("{496223C5-12B1-4329-A888-5640797BFCAD}");
        public static readonly ID TopLevelListClass = new ID("{EE039CE1-33C9-43EB-B7AB-AEB1C877F043}");
        public static readonly ID TopLevelListItemClass = new ID("{9DC9EBE7-C208-459C-8C77-286C6B6D5A11}");
    }
    public static class GeneratedNavigationRenderingParametersFieldNames
    {
        public const string TemplateName = "GeneratedNavigationRenderingParameters";
        public const string IncludeTopLevel = "IncludeTopLevel";
        public const string NavigationLevels = "NavigationLevels";
        public const string CssClass = "CssClass";
        public const string ChildLinkClass = "ChildLinkClass";
        public const string ChildListClass = "ChildListClass";
        public const string ChildListItemClass = "ChildListItemClass";
        public const string TopLevelLinkClass = "TopLevelLinkClass";
        public const string TopLevelListClass = "TopLevelListClass";
        public const string TopLevelListItemClass = "TopLevelListItemClass";
    }
}
namespace Elision.Fields
{
    public static class ColorSchemeFieldIDs
    {
        public static readonly ID TemplateId = new ID("{9F59984F-0638-4664-89D8-07B021D4D5A4}");
        public static readonly ID BackgroundColor = new ID("{503D6314-7B28-455B-AB54-E9D894479321}");
        public static readonly ID ForegroundColor = new ID("{91B68421-350B-4365-987B-AA2C45A902F6}");
    }
    public static class ColorSchemeFieldNames
    {
        public const string TemplateName = "ColorScheme";
        public const string BackgroundColor = "BackgroundColor";
        public const string ForegroundColor = "ForegroundColor";
    }
}
namespace Elision.Fields
{
    public static class SiteScriptsFieldIDs
    {
        public static readonly ID TemplateId = new ID("{A05913A9-FC8E-4E05-9741-61E480885E91}");
        public static readonly ID SiteFootScript = new ID("{52E994D5-E743-4DD6-9B86-60C7D170ED72}");
        public static readonly ID SiteHeadScript = new ID("{332BEBEB-F4E8-4078-A9CE-F718E69EC974}");
    }
    public static class SiteScriptsFieldNames
    {
        public const string TemplateName = "SiteScripts";
        public const string SiteFootScript = "SiteFootScript";
        public const string SiteHeadScript = "SiteHeadScript";
    }
}
namespace Elision.Fields
{
    public static class ContentBlockFieldIDs
    {
        public static readonly ID TemplateId = new ID("{A41FF548-E357-4C7F-ACF4-25D4A3759485}");
        public static readonly ID Copy = new ID("{9A5579B3-0558-45BA-9C28-DEF8B17B234A}");
    }
    public static class ContentBlockFieldNames
    {
        public const string TemplateName = "ContentBlock";
        public const string Copy = "Copy";
    }
}
namespace Elision.Fields
{
    public static class RenderingFolderWithAreaFieldIDs
    {
        public static readonly ID TemplateId = new ID("{ACC5FB47-950F-45FA-A6A7-15C1C681CBA7}");
        public static readonly ID AreaName = new ID("{2E1C630C-AC9F-473C-ABCD-DB8CA1DE0ACB}");
    }
    public static class RenderingFolderWithAreaFieldNames
    {
        public const string TemplateName = "RenderingFolderWithArea";
        public const string AreaName = "AreaName";
    }
}
namespace Elision.Fields
{
    public static class ResponsiveImageSizeFieldIDs
    {
        public static readonly ID TemplateId = new ID("{AF7849FC-069E-4EC1-82FF-065AC40C9DF3}");
        public static readonly ID ImageWidth = new ID("{2D396085-0373-45E0-AD3F-10D5676D7367}");
        public static readonly ID WindowMinWidth = new ID("{A0819F72-60D2-41B7-8F7D-E1955BEB22AF}");
    }
    public static class ResponsiveImageSizeFieldNames
    {
        public const string TemplateName = "ResponsiveImageSize";
        public const string ImageWidth = "ImageWidth";
        public const string WindowMinWidth = "WindowMinWidth";
    }
}
namespace Elision.Fields
{
    public static class AreaNameFieldIDs
    {
        public static readonly ID TemplateId = new ID("{BD57D269-42CE-416C-8B18-C7E3733DA626}");
        public static readonly ID AreaName = new ID("{2E1C630C-AC9F-473C-ABCD-DB8CA1DE0ACB}");
    }
    public static class AreaNameFieldNames
    {
        public const string TemplateName = "AreaName";
        public const string AreaName = "AreaName";
    }
}
namespace Elision.Fields
{
    public static class HeadingLevelFieldsFieldIDs
    {
        public static readonly ID TemplateId = new ID("{C1017F17-722B-4DA8-931C-6A246D16C47C}");
        public static readonly ID HeadingLevel = new ID("{3D0F3166-9579-494E-A76C-75E5A47BB451}");
    }
    public static class HeadingLevelFieldsFieldNames
    {
        public const string TemplateName = "HeadingLevelFields";
        public const string HeadingLevel = "HeadingLevel";
    }
}
namespace Elision.Fields
{
    public static class RobotsTxtGenerationFieldIDs
    {
        public static readonly ID TemplateId = new ID("{C7765445-5959-4168-9509-EDD3EFFEC41E}");
        public static readonly ID RobotsTxt = new ID("{95CFE1F9-8B50-4911-838C-67289079411A}");
    }
    public static class RobotsTxtGenerationFieldNames
    {
        public const string TemplateName = "RobotsTxtGeneration";
        public const string RobotsTxt = "RobotsTxt";
    }
}
namespace Elision.Fields
{
    public static class HeadingFieldIDs
    {
        public static readonly ID TemplateId = new ID("{CE1B093D-CF02-4805-B54E-96D02C6954D5}");
        public static readonly ID HeadingText = new ID("{8625E3CB-8662-42CC-9156-B94D2872058B}");
    }
    public static class HeadingFieldNames
    {
        public const string TemplateName = "Heading";
        public const string HeadingText = "HeadingText";
    }
}
namespace Elision.Fields
{
    public static class ThemeResourceFieldIDs
    {
        public static readonly ID TemplateId = new ID("{D522F52B-09DF-442D-84A9-17A497C00BCC}");
        public static readonly ID PageModes = new ID("{B7100C64-8316-44E7-926D-9F2FE164CD69}");
        public static readonly ID ResourceLocation = new ID("{575073A1-3DEF-47E6-B62A-D5BD2F94D6A7}");
        public static readonly ID SupportedDevices = new ID("{70AA35E0-E88C-4504-A512-58BBB4D10AAA}");
    }
    public static class ThemeResourceFieldNames
    {
        public const string TemplateName = "ThemeResource";
        public const string PageModes = "PageModes";
        public const string ResourceLocation = "ResourceLocation";
        public const string SupportedDevices = "SupportedDevices";
    }
}
namespace Elision.Fields
{
    public static class ContentPageFieldIDs
    {
        public static readonly ID TemplateId = new ID("{D5950FBE-F4A5-45CB-BD88-6EE0B8BEEC54}");
        public static readonly ID PageFootScript = new ID("{A3644CDE-C5EA-4521-82C6-0D85D1CFEA8C}");
        public static readonly ID PageHeadScript = new ID("{C6D8E03E-B82B-4D2C-93C9-8170249F1E02}");
        public static readonly ID BlockSearchEngineIndexing = new ID("{0ED18C8B-E06A-4F49-8F9E-8346F1A3294C}");
        public static readonly ID BlockSearchEngineLinkFollowing = new ID("{7FB8D83D-C981-49D9-B352-953E5C6BE7CF}");
        public static readonly ID BrowserTitle = new ID("{D6CB41B5-9467-4C42-95AC-B62584A1F5F0}");
        public static readonly ID CanonicalUrl = new ID("{C0AD316F-EEC8-494D-A30A-356C10E8853E}");
        public static readonly ID MetaDescription = new ID("{D62C4448-2E23-4393-939D-F489DCFB881E}");
        public static readonly ID MetaKeywords = new ID("{DEAD7283-98C8-4AB8-924E-0DEB00858EFB}");
        public static readonly ID NavigationText = new ID("{9638B7BE-396E-4A34-B050-F3AB26826229}");
        public static readonly ID ShowInInteriorNavigation = new ID("{F70C036B-6D13-4C73-8E18-D247DAAB5B1F}");
        public static readonly ID ShowInPrimaryNavigation = new ID("{20F9494E-0190-47A0-8A5B-E64F67E801B9}");
        public static readonly ID CascadePlaceholders = new ID("{03AD4613-0167-420A-8B3F-3CB6CCF3B738}");
        public static readonly ID HideFromSiteSearch = new ID("{3C4D4755-8FB1-40F2-B236-BE1E0B552A84}");
        public static readonly ID TwitterCardContentCreator = new ID("{F4DED7B3-8B6F-46D8-902C-1C119BDA1699}");
        public static readonly ID TwitterCardDescription = new ID("{5B3DD1A3-40F8-42BE-900E-53FA38195AF1}");
        public static readonly ID TwitterCardImage = new ID("{BA3C147E-035B-478F-829B-FE233775648F}");
        public static readonly ID TwitterCardSite = new ID("{BA005D3B-393D-4594-8508-70A503925DCD}");
        public static readonly ID TwitterCardSiteId = new ID("{217988BC-4DDE-4B44-A688-DFB8F69C6061}");
        public static readonly ID TwitterCardTitle = new ID("{0181FE49-A838-496D-8690-935282E599F3}");
        public static readonly ID TwitterCardType = new ID("{579ED843-06B5-4E31-9B98-0D4B12E418AB}");
    }
    public static class ContentPageFieldNames
    {
        public const string TemplateName = "ContentPage";
        public const string PageFootScript = "PageFootScript";
        public const string PageHeadScript = "PageHeadScript";
        public const string BlockSearchEngineIndexing = "BlockSearchEngineIndexing";
        public const string BlockSearchEngineLinkFollowing = "BlockSearchEngineLinkFollowing";
        public const string BrowserTitle = "BrowserTitle";
        public const string CanonicalUrl = "CanonicalUrl";
        public const string MetaDescription = "MetaDescription";
        public const string MetaKeywords = "MetaKeywords";
        public const string NavigationText = "NavigationText";
        public const string ShowInInteriorNavigation = "ShowInInteriorNavigation";
        public const string ShowInPrimaryNavigation = "ShowInPrimaryNavigation";
        public const string CascadePlaceholders = "CascadePlaceholders";
        public const string HideFromSiteSearch = "HideFromSiteSearch";
        public const string TwitterCardContentCreator = "TwitterCardContentCreator";
        public const string TwitterCardDescription = "TwitterCardDescription";
        public const string TwitterCardImage = "TwitterCardImage";
        public const string TwitterCardSite = "TwitterCardSite";
        public const string TwitterCardSiteId = "TwitterCardSiteId";
        public const string TwitterCardTitle = "TwitterCardTitle";
        public const string TwitterCardType = "TwitterCardType";
    }
}
namespace Elision.Fields
{
    public static class LanguageAutoPublishFieldIDs
    {
        public static readonly ID TemplateId = new ID("{D5EEE650-7002-4163-A12E-58A13B391B06}");
        public static readonly ID AutoPublish = new ID("{1C8DA681-5269-48EF-A055-A3DA227FD830}");
    }
    public static class LanguageAutoPublishFieldNames
    {
        public const string TemplateName = "LanguageAutoPublish";
        public const string AutoPublish = "AutoPublish";
    }
}
namespace Elision.Fields
{
    public static class MenuLinkFieldIDs
    {
        public static readonly ID TemplateId = new ID("{D661EDF4-40A8-4217-9EFA-31395ACB498E}");
        public static readonly ID Link = new ID("{D0F1890A-8739-4CFF-B38A-6883838FEE19}");
    }
    public static class MenuLinkFieldNames
    {
        public const string TemplateName = "MenuLink";
        public const string Link = "Link";
    }
}
namespace Elision.Fields
{
    public static class PageScriptsFieldIDs
    {
        public static readonly ID TemplateId = new ID("{DB1E7728-506A-4D2F-A9F7-9172692D4A71}");
        public static readonly ID PageFootScript = new ID("{A3644CDE-C5EA-4521-82C6-0D85D1CFEA8C}");
        public static readonly ID PageHeadScript = new ID("{C6D8E03E-B82B-4D2C-93C9-8170249F1E02}");
    }
    public static class PageScriptsFieldNames
    {
        public const string TemplateName = "PageScripts";
        public const string PageFootScript = "PageFootScript";
        public const string PageHeadScript = "PageHeadScript";
    }
}
namespace Elision.Fields
{
    public static class OptionFieldIDs
    {
        public static readonly ID TemplateId = new ID("{E226523E-AD24-45A1-B5D6-74E11F61DBC1}");
    }
    public static class OptionFieldNames
    {
        public const string TemplateName = "Option";
    }
}
namespace Elision.Fields
{
    public static class WebsiteFolderFieldIDs
    {
        public static readonly ID TemplateId = new ID("{E87C2B17-E271-4DD2-AAA7-6CDD3D39FD0A}");
        public static readonly ID Theme = new ID("{F318342F-A549-47F7-BD88-25086B46B9D9}");
    }
    public static class WebsiteFolderFieldNames
    {
        public const string TemplateName = "WebsiteFolder";
        public const string Theme = "Theme";
    }
}
namespace Elision.Fields
{
    public static class NavigationCssClassesFieldsFieldIDs
    {
        public static readonly ID TemplateId = new ID("{E978C2A9-C6E5-486C-A46C-ABFA5EC84C5C}");
        public static readonly ID ChildLinkClass = new ID("{5A6FCBB2-93C4-4458-8ACC-9AB713341055}");
        public static readonly ID ChildListClass = new ID("{C6EF88F6-CF6E-4415-9079-484950A4581F}");
        public static readonly ID ChildListItemClass = new ID("{9DE25D2B-4935-4A06-ACA2-BB56ED526A3C}");
        public static readonly ID TopLevelLinkClass = new ID("{496223C5-12B1-4329-A888-5640797BFCAD}");
        public static readonly ID TopLevelListClass = new ID("{EE039CE1-33C9-43EB-B7AB-AEB1C877F043}");
        public static readonly ID TopLevelListItemClass = new ID("{9DC9EBE7-C208-459C-8C77-286C6B6D5A11}");
    }
    public static class NavigationCssClassesFieldsFieldNames
    {
        public const string TemplateName = "NavigationCssClassesFields";
        public const string ChildLinkClass = "ChildLinkClass";
        public const string ChildListClass = "ChildListClass";
        public const string ChildListItemClass = "ChildListItemClass";
        public const string TopLevelLinkClass = "TopLevelLinkClass";
        public const string TopLevelListClass = "TopLevelListClass";
        public const string TopLevelListItemClass = "TopLevelListItemClass";
    }
}
namespace Elision.Fields
{
    public static class HomePageFieldIDs
    {
        public static readonly ID TemplateId = new ID("{E9B6FBA3-AF11-429B-9709-CEDD0087E57D}");
        public static readonly ID PageFootScript = new ID("{A3644CDE-C5EA-4521-82C6-0D85D1CFEA8C}");
        public static readonly ID PageHeadScript = new ID("{C6D8E03E-B82B-4D2C-93C9-8170249F1E02}");
        public static readonly ID BlockSearchEngineIndexing = new ID("{0ED18C8B-E06A-4F49-8F9E-8346F1A3294C}");
        public static readonly ID BlockSearchEngineLinkFollowing = new ID("{7FB8D83D-C981-49D9-B352-953E5C6BE7CF}");
        public static readonly ID BrowserTitle = new ID("{D6CB41B5-9467-4C42-95AC-B62584A1F5F0}");
        public static readonly ID CanonicalUrl = new ID("{C0AD316F-EEC8-494D-A30A-356C10E8853E}");
        public static readonly ID MetaDescription = new ID("{D62C4448-2E23-4393-939D-F489DCFB881E}");
        public static readonly ID MetaKeywords = new ID("{DEAD7283-98C8-4AB8-924E-0DEB00858EFB}");
        public static readonly ID NavigationText = new ID("{9638B7BE-396E-4A34-B050-F3AB26826229}");
        public static readonly ID ShowInInteriorNavigation = new ID("{F70C036B-6D13-4C73-8E18-D247DAAB5B1F}");
        public static readonly ID ShowInPrimaryNavigation = new ID("{20F9494E-0190-47A0-8A5B-E64F67E801B9}");
        public static readonly ID CascadePlaceholders = new ID("{03AD4613-0167-420A-8B3F-3CB6CCF3B738}");
        public static readonly ID HideFromSiteSearch = new ID("{3C4D4755-8FB1-40F2-B236-BE1E0B552A84}");
        public static readonly ID TwitterCardContentCreator = new ID("{F4DED7B3-8B6F-46D8-902C-1C119BDA1699}");
        public static readonly ID TwitterCardDescription = new ID("{5B3DD1A3-40F8-42BE-900E-53FA38195AF1}");
        public static readonly ID TwitterCardImage = new ID("{BA3C147E-035B-478F-829B-FE233775648F}");
        public static readonly ID TwitterCardSite = new ID("{BA005D3B-393D-4594-8508-70A503925DCD}");
        public static readonly ID TwitterCardSiteId = new ID("{217988BC-4DDE-4B44-A688-DFB8F69C6061}");
        public static readonly ID TwitterCardTitle = new ID("{0181FE49-A838-496D-8690-935282E599F3}");
        public static readonly ID TwitterCardType = new ID("{579ED843-06B5-4E31-9B98-0D4B12E418AB}");
        public static readonly ID SiteFootScript = new ID("{52E994D5-E743-4DD6-9B86-60C7D170ED72}");
        public static readonly ID SiteHeadScript = new ID("{332BEBEB-F4E8-4078-A9CE-F718E69EC974}");
        public static readonly ID Theme = new ID("{F318342F-A549-47F7-BD88-25086B46B9D9}");
        public static readonly ID SitemapXmlInitialQuery = new ID("{6F6F73C6-E61B-4B35-84BA-60A1D8C49D88}");
        public static readonly ID SitemapXmlRules = new ID("{8020FB72-2860-4899-833A-587D26743675}");
        public static readonly ID RobotsTxt = new ID("{95CFE1F9-8B50-4911-838C-67289079411A}");
    }
    public static class HomePageFieldNames
    {
        public const string TemplateName = "HomePage";
        public const string PageFootScript = "PageFootScript";
        public const string PageHeadScript = "PageHeadScript";
        public const string BlockSearchEngineIndexing = "BlockSearchEngineIndexing";
        public const string BlockSearchEngineLinkFollowing = "BlockSearchEngineLinkFollowing";
        public const string BrowserTitle = "BrowserTitle";
        public const string CanonicalUrl = "CanonicalUrl";
        public const string MetaDescription = "MetaDescription";
        public const string MetaKeywords = "MetaKeywords";
        public const string NavigationText = "NavigationText";
        public const string ShowInInteriorNavigation = "ShowInInteriorNavigation";
        public const string ShowInPrimaryNavigation = "ShowInPrimaryNavigation";
        public const string CascadePlaceholders = "CascadePlaceholders";
        public const string HideFromSiteSearch = "HideFromSiteSearch";
        public const string TwitterCardContentCreator = "TwitterCardContentCreator";
        public const string TwitterCardDescription = "TwitterCardDescription";
        public const string TwitterCardImage = "TwitterCardImage";
        public const string TwitterCardSite = "TwitterCardSite";
        public const string TwitterCardSiteId = "TwitterCardSiteId";
        public const string TwitterCardTitle = "TwitterCardTitle";
        public const string TwitterCardType = "TwitterCardType";
        public const string SiteFootScript = "SiteFootScript";
        public const string SiteHeadScript = "SiteHeadScript";
        public const string Theme = "Theme";
        public const string SitemapXmlInitialQuery = "SitemapXmlInitialQuery";
        public const string SitemapXmlRules = "SitemapXmlRules";
        public const string RobotsTxt = "RobotsTxt";
    }
}
namespace Elision.Fields
{
    public static class TextAlignFieldsFieldIDs
    {
        public static readonly ID TemplateId = new ID("{EA6D7B0F-FFEF-4989-A2AA-37F9B980E0D1}");
        public static readonly ID TextAlign = new ID("{144EF311-3003-40AF-AC2C-DDEED3D4A64D}");
    }
    public static class TextAlignFieldsFieldNames
    {
        public const string TemplateName = "TextAlignFields";
        public const string TextAlign = "TextAlign";
    }
}
namespace Elision.Fields
{
    public static class LanguageFieldIDs
    {
        public static readonly ID TemplateId = new ID("{F68F13A6-3395-426A-B9A1-FA2DC60D94EB}");
    }
    public static class LanguageFieldNames
    {
        public const string TemplateName = "Language";
    }
}
namespace Elision.Fields
{
    public static class SitemapXmlGenerationFieldIDs
    {
        public static readonly ID TemplateId = new ID("{F75F0FC8-07E6-4E43-A97A-66DAAB31009A}");
        public static readonly ID SitemapXmlInitialQuery = new ID("{6F6F73C6-E61B-4B35-84BA-60A1D8C49D88}");
        public static readonly ID SitemapXmlRules = new ID("{8020FB72-2860-4899-833A-587D26743675}");
    }
    public static class SitemapXmlGenerationFieldNames
    {
        public const string TemplateName = "SitemapXmlGeneration";
        public const string SitemapXmlInitialQuery = "SitemapXmlInitialQuery";
        public const string SitemapXmlRules = "SitemapXmlRules";
    }
}
